apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-api-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: clouds-api
  - name: git-url
    value: https://github.com/domenecsos/OpenShift-Multi-Cluster-Management-Handbook.git
  - name: IMAGE
    value: 10.210.4.120:5000/pipelines-sample/clouds-api
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
